### ISSUE TITLE
Python 3.6: ModuleNotFoundError: No module named 'dataclasses'

### ISSUE THREAD

**Issue by williamjmorenor** [spapanik/teritorio#1]
Looks like with Python 3.6 there is not dataclass module to import

    import json
>   from dataclasses import dataclass
E   ModuleNotFoundError: No module named 'dataclasses'

https://github.com/cacao-accounting/cacao-accounting/runs/996592580?check_suite_focus=true

**Comment by spapanik** [comment]
Support for python 3.6 is now in master, and will be included in the next release.

**Comment by spapanik** [comment]
Fixed in [v1.1.0](https://github.com/spapanik/teritorio/tree/v1.1.0)

**Comment by williamjmorenor** [comment]
Thanks a lot 👍
